export const ABLY_KEY = "UjnnTg.KNgjJA:EUHHuL1WoOc7J9RoZmuzG_Or6wLUd3b5LqMAqbyztHg";
export const ROUND_TIME = 90;
export const TOTAL_ROUNDS = 3;

export const COLORS = [
  "#000000","#e94560","#ff9f43","#f9ca24","#6ab04c",
  "#22a6b3","#4834d4","#be2edd","#ffffff","#aaaaaa","#795548","#ff6b81"
];

export const WORDS: Record<string, string[]> = {
  animals: [
    "dog","cat","elephant","giraffe","lion","tiger","zebra","panda","kangaroo","dolphin",
    "whale","shark","octopus","penguin","rabbit","horse","cow","goat","sheep","monkey",
    "gorilla","camel","deer","fox","wolf","bear","koala","otter","parrot","eagle",
    "owl","peacock","flamingo","crocodile","alligator","turtle","frog","snake","lizard",
  ],
  food: [
    "pizza","burger","sandwich","taco","burrito","sushi","ramen","pasta","spaghetti","noodles",
    "donut","croissant","waffle","pancake","cake","cookie","ice cream","apple","banana","orange",
    "grapes","watermelon","pineapple","mango","coconut","carrot","potato","tomato","broccoli",
    "cheese","egg","sausage","hotdog","popcorn","chocolate","cupcake","milkshake","curry","samosa","pretzel",
  ],
  objects: [
    "chair","table","lamp","clock","mirror","phone","laptop","keyboard","mouse","camera",
    "wallet","umbrella","bottle","cup","plate","spoon","fork","knife","toothbrush","book",
    "notebook","pencil","eraser","scissors","hammer","wrench","ladder","binoculars",
    "backpack","suitcase","helmet","gloves","belt","scarf","ring","necklace","bracelet","sunglasses",
    "candle","pillow","blanket","curtain","vase","frame","trophy","medal","ticket","stamp",
    "envelope","tape","stapler","pin","magnet","battery","bulb","plug","socket","cable",
    "bucket","broom","mop","dustpan","shovel","axe","saw","drill","nail","screw",
    "rope","chain","lock","key","compass","ruler","microscope","magnifier","telescope","calculator",
    "watch","alarm","radio","remote","headphones","speaker","microphone","projector","lantern","torch",
    "pan","pot","kettle","spatula","whisk","grater","colander","tray","bowl","jar",
    "corkscrew","bottle opener","peeler","ladle","rolling pin","chopping board","apron","oven mitt","thermos","lunchbox",
    "sofa","bed","wardrobe","drawer","shelf","cabinet","stool","bench","hammock","mat",
    "doorbell","mailbox","fire extinguisher","fire alarm","safe","padlock","hinge","hook","bracket","lever",
    "brush","comb","razor","tweezers","nail clipper","hairdryer","shampoo","soap","sponge","towel",
    "map","globe","atlas","diary","calendar","receipt","coupon","badge","lanyard","folder",
    "easel","palette","paintbrush","canvas","sketchbook","crayon","marker","highlighter","ink","stamp pad",
    "dart","dice","chess piece","playing card","jigsaw","yo-yo","kite","frisbee","boomerang","slingshot",
    "tent","sleeping bag","canteen","compass","matchbox","lighter","whistle","carabiner","pulley","winch",
  ],
  vehicles: [
    "car","bus","truck","motorcycle","bicycle","scooter","train","tram","subway","airplane",
    "helicopter","rocket","boat","ship","submarine","canoe","kayak","ambulance","fire truck",
    "police car","tractor","bulldozer","crane","race car","hot air balloon",
    "van","minibus","limousine","pickup truck","monster truck","jeep","tank","forklift","dumper","steamroller",
    "glider","jet","fighter jet","cargo plane","seaplane","parachute","hang glider","paraglider","blimp","zeppelin",
    "sailboat","yacht","catamaran","hovercraft","speedboat","ferry","tugboat","aircraft carrier","cruise ship","tanker",
    "skateboard","roller skates","unicycle","go-kart","quad bike","snowmobile","dog sled","rickshaw","chariot","gondola",
    "space shuttle","space station","rover","cable car","monorail","trolleybus","segway","jet ski","airboat","hydrofoil",
    "sports car","convertible","SUV","sedan","hatchback","station wagon","coupe","electric car","self-driving car","armored car",
    "garbage truck","cement mixer","snow plow","street sweeper","logging truck","flatbed truck","ice cream truck","food truck","tow truck","oil tanker truck",
    "steam train","bullet train","freight train","maglev train","funicular","chairlift","ski lift","gondola lift","people mover","light rail",
    "warship","destroyer","battleship","frigate","patrol boat","lifeboat","icebreaker","drilling ship","fishing boat","rowboat",
    "biplane","propeller plane","spy plane","stealth bomber","drone","paramotor","microlight","crop duster","air ambulance","jumbo jet",
    "moon buggy","probe","lander","capsule","rocket ship","space probe","satellite","space telescope","ion drive","warp ship",
  ],
  places: [
    "school","library","museum","hospital","airport","train station","castle","palace","beach",
    "park","zoo","aquarium","restaurant","hotel","stadium","theater","factory","farm","bridge",
    "lighthouse","waterfall","volcano","mountain","forest","desert","island","cave","temple","church","market",
    "bakery","pharmacy","bank","post office","fire station","police station","courthouse","prison","embassy","city hall",
    "shopping mall","supermarket","gas station","parking lot","cinema","nightclub","bar","cafe","salon","spa",
    "gym","swimming pool","skating rink","bowling alley","golf course","racetrack","boxing ring","ski resort","campsite","playground",
    "harbor","pier","dock","lighthouse","canal","dam","power plant","wind farm","solar farm","oil rig",
    "rainforest","jungle","savanna","tundra","glacier","coral reef","swamp","meadow","valley","canyon",
    "skyscraper","apartment","cottage","mansion","igloo","treehouse","houseboat","bunker","fortress","ruins",
    "classroom","laboratory","operating room","courtroom","office","studio","garage","attic","basement","rooftop",
    "subway station","bus stop","toll booth","border crossing","checkpoint","space center","observatory","planetarium","winery","brewery",
    "cathedral","mosque","synagogue","shrine","monastery","convent","pagoda","pyramid","sphinx","colosseum",
    "greenhouse","botanical garden","arboretum","national park","nature reserve","wildlife sanctuary","bird sanctuary","game reserve","safari park","marine park",
    "art gallery","sculpture garden","wax museum","haunted house","escape room","amusement park","water park","theme park","carnival","fairground",
    "university","college","kindergarten","boarding school","academy","training center","language school","driving school","flight school","medical school",
    "stock exchange","auction house","pawn shop","flea market","craft fair","farmers market","night market","fish market","flower market","antique shop",
    "laundromat","dry cleaner","tailor shop","shoe repair","locksmith","print shop","photo studio","recording studio","film studio","animation studio",
    "nuclear plant","hydroelectric dam","geothermal plant","coal mine","gold mine","quarry","oil field","refinery","steel mill","shipyard",
    "orphanage","nursing home","daycare","rehab center","mental hospital","veterinary clinic","blood bank","morgue","crematorium","cemetery",
    "embassy","consulate","parliament","senate","white house","kremlin","pentagon","intelligence agency","military base","naval base",
  ],
  professions: [
    "doctor","nurse","teacher","chef","pilot","farmer","firefighter","police officer","engineer",
    "scientist","artist","musician","actor","writer","dentist","mechanic","astronaut","carpenter",
    "electrician","plumber",
    "lawyer","judge","accountant","banker","architect","designer","photographer","journalist","editor","publisher",
    "programmer","hacker","data scientist","animator","game developer","web designer","IT support","cybersecurity","AI engineer","software tester",
    "surgeon","pediatrician","psychiatrist","pharmacist","radiologist","paramedic","midwife","therapist","dietitian","optometrist",
    "principal","professor","librarian","tutor","coach","counselor","social worker","psychologist","speech therapist","special educator",
    "painter","sculptor","illustrator","comic artist","graffiti artist","tattoo artist","fashion designer","interior designer","jeweler","potter",
    "singer","guitarist","drummer","pianist","DJ","composer","conductor","sound engineer","radio host","podcaster",
    "baker","butcher","barista","bartender","waiter","sommelier","food critic","caterer","nutritionist","food scientist",
    "soldier","general","admiral","spy","detective","bodyguard","security guard","border agent","coast guard","ranger",
    "sailor","captain","navigator","diver","lifeguard","skipper","fisherman","lumberjack","miner","oil driller",
    "tailor","cobbler","watchmaker","glassblower","blacksmith","welder","plumber","bricklayer","roofer","plasterer",
    "vet","zookeeper","dog trainer","horse trainer","beekeeper","florist","gardener","landscaper","forester","ecologist",
    "astronomer","geologist","chemist","physicist","biologist","archaeologist","anthropologist","historian","philosopher","economist",
    "athlete","referee","coach","sports commentator","personal trainer","yoga instructor","gymnast","jockey","caddy","scout",
    "politician","diplomat","ambassador","mayor","senator","lobbyist","activist","journalist","news anchor","publicist",
    "entrepreneur","CEO","manager","salesperson","marketing director","brand strategist","recruiter","HR manager","auditor","consultant",
    "librarian","archivist","curator","conservator","translator","interpreter","tour guide","travel agent","event planner","wedding planner",
  ],
  sports: [
    "football","cricket","basketball","tennis","badminton","golf","rugby","volleyball","baseball",
    "hockey","boxing","wrestling","swimming","cycling","surfing","skiing","archery","bowling",
    "skateboarding","table tennis",
    "running","sprinting","marathon","hurdles","long jump","high jump","pole vault","shot put","discus","javelin",
    "rowing","kayaking","canoeing","water polo","diving","snorkeling","triathlon","pentathlon","decathlon","biathlon",
    "fencing","judo","karate","taekwondo","sumo","kickboxing","muay thai","gymnastics","rhythmic gymnastics","trampolining",
    "horse riding","polo","rodeo","bull riding","luge","bobsled","curling","ice skating","figure skating","speed skating",
    "rock climbing","bungee jumping","paragliding","skydiving","motocross","rally racing","drag racing","snowboarding","freestyle skiing","cross country skiing",
    "darts","snooker","billiards","chess boxing","arm wrestling","tug of war","dodgeball","lacrosse","squash","handball",
    "softball","netball","futsal","kabaddi","sepak takraw","ultimate frisbee","parkour","breakdancing","esports","drone racing",
    "sailing","windsurfing","kitesurfing","wakeboarding","waterskiing","cliff diving","synchronized swimming","open water swimming","canoe polo","dragon boat",
    "mountain biking","BMX","road cycling","velodrome","cyclocross","unicycling","trial biking","downhill racing","enduro","gravel racing",
    "weightlifting","powerlifting","bodybuilding","crossfit","kettlebell","calisthenics","yoga","pilates","tai chi","qigong",
    "orienteering","fell running","obstacle course","mud run","spartan race","iron man","ultramarathon","racewalking","nordic walking","stair climbing",
    "polo","elephant polo","camel racing","greyhound racing","pigeon racing","falconry","dog sledding","ox racing","chariot racing","jousting",
    "air hockey","foosball","pinball","laser tag","paintball","airsoft","bubble football","chess","poker","mahjong",
    "rhythmic gymnastics","aerial acrobatics","circus arts","fire spinning","sword swallowing","tightrope walking","trapeze","baton twirling","cheerleading","flag football",
  ],
  nature: [
    "tree","flower","rose","sunflower","tulip","cactus","mushroom","cloud","rainbow","river",
    "lake","ocean","sun","moon","star","planet","galaxy","comet","meteor","snowflake",
    "thunder","lightning","tornado","hurricane","leaf",
    "oak","pine","palm","bamboo","willow","maple","cherry blossom","mangrove","fern","moss",
    "coral","seaweed","kelp","algae","lily pad","lotus","orchid","lavender","daisy","dandelion",
    "iceberg","glacier","avalanche","landslide","earthquake","tsunami","flood","drought","wildfire","blizzard",
    "sand dune","salt flat","hot spring","geyser","mud pool","sinkhole","cliff","gorge","plateau","delta",
    "aurora","fog","mist","hail","sleet","frost","dew","heatwave","monsoon","typhoon",
    "waterfall","rapids","estuary","lagoon","fjord","atoll","reef","trench","peninsula","archipelago",
    "pebble","boulder","crystal","fossil","volcano","lava","magma","stalagmite","stalactite","geode",
    "soil","sand","clay","gravel","mud","peat","compost","roots","bark","thorn",
    "honey","pollen","spore","seed","berry","acorn","pinecone","pod","vine","ivy",
    "sunset","sunrise","eclipse","solstice","equinox","tide","current","wave","breeze","gust",
  ],
  technology: [
    "computer","server","robot","drone","satellite","telescope","microscope","calculator","printer",
    "router","microchip","sensor","battery","headphones","smartwatch","tablet","monitor","webcam",
    "joystick","game console",
    "smartphone","charger","power bank","SIM card","hard drive","USB drive","memory card","graphics card","CPU","RAM",
    "motherboard","cooling fan","heat sink","power supply","circuit board","transistor","capacitor","resistor","LED","laser",
    "keyboard","mouse pad","touchscreen","stylus","trackpad","scanner","barcode reader","fingerprint reader","face scanner","retina scanner",
    "3D printer","laser cutter","CNC machine","soldering iron","multimeter","oscilloscope","voltmeter","ammeter","spectrum analyzer","signal generator",
    "wifi","bluetooth","NFC","infrared","radio tower","antenna","modem","switch","firewall","ethernet cable",
    "cloud","data center","mainframe","supercomputer","quantum computer","neural network","AI chip","GPU cluster","edge device","IoT sensor",
    "smartwatch","smart glasses","VR headset","AR headset","haptic glove","exoskeleton","brain implant","bionic arm","smart ring","fitness tracker",
    "ATM","POS terminal","vending machine","ticket machine","kiosk","self-checkout","digital billboard","e-reader","smart TV","set-top box",
    "electric motor","generator","transformer","inverter","solar panel","wind turbine","fuel cell","nuclear reactor","particle accelerator","MRI machine",
    "radar","sonar","lidar","GPS","black box","flight computer","autopilot","cruise control","ABS system","CCTV camera",
  ],
  geometry: [
    "circle","square","triangle","rectangle","pentagon","hexagon","heptagon","octagon","nonagon","decagon",
    "oval","ellipse","diamond","rhombus","trapezoid","parallelogram","kite","star","crescent","cross",
    "cube","sphere","cylinder","cone","pyramid","prism","cuboid","torus","tetrahedron","octahedron",
    "dodecahedron","icosahedron","hemisphere","capsule","frustum","wedge","arch","helix","spiral","parabola",
    "point","line","ray","segment","angle","right angle","acute angle","obtuse angle","reflex angle","straight angle",
    "perpendicular","parallel","diagonal","bisector","tangent","chord","radius","diameter","circumference","arc",
    "polygon","quadrilateral","scalene","isosceles","equilateral","concave","convex","regular","irregular","symmetric",
    "area","perimeter","volume","surface area","hypotenuse","altitude","median","centroid","vertex","edge",
    "face","net","cross section","axis","origin","coordinate","grid","plane","depth","dimension",
    "fractal","tessellation","venn diagram","pie chart","bar chart","number line","matrix","vector","angle bisector","midpoint",
  ],
  body: [
    "head","face","neck","shoulder","arm","elbow","wrist","hand","finger","thumb",
    "chest","back","spine","rib","hip","waist","belly","stomach","leg","knee",
    "ankle","foot","toe","heel","calf","thigh","groin","armpit","collarbone","shoulder blade",
    "eye","eyebrow","eyelid","eyelash","nose","nostril","ear","eardrum","mouth","lip",
    "tongue","tooth","gum","jaw","cheek","chin","forehead","temple","skull","brain",
    "heart","lung","liver","kidney","stomach","intestine","bladder","pancreas","spleen","appendix",
    "vein","artery","nerve","muscle","tendon","ligament","cartilage","bone","joint","skin",
    "hair","nail","pore","freckle","dimple","wrinkle","scar","birthmark","pupil","iris",
    "palm","knuckle","shin","kneecap","pelvis","sternum","trachea","esophagus","larynx","diaphragm",
  ],
  clothing: [
    "shirt","t-shirt","polo shirt","dress shirt","blouse","tank top","crop top","hoodie","sweatshirt","sweater",
    "jacket","blazer","coat","trench coat","raincoat","windbreaker","cardigan","vest","poncho","cape",
    "trousers","jeans","shorts","skirt","mini skirt","leggings","tracksuit","sweatpants","cargo pants","chinos",
    "dress","gown","saree","kimono","kurta","kilt","jumpsuit","romper","overalls","uniform",
    "underwear","bra","boxer shorts","socks","tights","stockings","swimsuit","bikini","wetsuit","lingerie",
    "shoes","sneakers","boots","heels","sandals","flip flops","loafers","oxford shoes","stilettos","clogs",
    "hat","cap","beanie","beret","turban","crown","headband","visor","top hat","cowboy hat",
    "collar","lapel","cuff","sleeve","hem","pocket","button","zipper","lace","strap",
    "belt","tie","bow tie","scarf","gloves","mittens","sunglasses","watch","bracelet","handbag",
    "hood","lining","seam","waistband","neckline","pleat","ruffle","fringe","patch","embroidery",
  ],
  colors: [
    "red","blue","green","yellow","orange","purple","pink","brown","black","white",
    "grey","silver","gold","beige","cream","ivory","maroon","crimson","scarlet","ruby",
    "navy","cobalt","royal blue","sky blue","turquoise","teal","cyan","mint","aqua","indigo",
    "violet","lavender","lilac","magenta","fuchsia","rose","salmon","coral","peach","apricot",
    "olive","lime","emerald","jade","forest green","sage","khaki","tan","caramel","chocolate",
    "wine","burgundy","rust","copper","bronze","amber","mustard","lemon","champagne","platinum",
    "charcoal","slate","ash","smoke","obsidian","pearl","nude","blush","sand","terracotta",
  ],
  biology: [
    "amoeba","bacteria","virus","fungi","algae","protozoa","parasite","pathogen","microbe","germ",
    "cell","nucleus","membrane","mitochondria","chromosome","DNA","RNA","protein","enzyme","hormone",
    "antibody","vaccine","immune system","white blood cell","red blood cell","platelet","plasma","blood","lymph","tissue",
    "photosynthesis","respiration","digestion","metabolism","evolution","mutation","gene","genome","clone","stem cell",
    "ecosystem","food chain","predator","prey","symbiosis","parasite","host","pollination","germination","decomposition",
    "coral","plankton","spore","mold","yeast","mushroom","lichen","moss","fern","seed",
    "skeleton","exoskeleton","shell","fin","gill","wing","antenna","tentacle","claw","fang",
  ],
  daily: [
    "alarm clock","toothbrush","toothpaste","soap","shampoo","towel","comb","razor","mirror","deodorant",
    "breakfast","coffee","tea","newspaper","backpack","keys","wallet","phone","earphones","charger",
    "lunch box","water bottle","umbrella","bus pass","badge","pen","notebook","calendar","sticky note","stapler",
    "dinner","plate","glass","fork","knife","spoon","napkin","tablecloth","candle","coaster",
    "trash can","recycle bin","mop","broom","vacuum cleaner","detergent","sponge","dish rack","laundry basket","clothesline",
    "pillow","blanket","alarm","curtain","nightlight","doormat","welcome mat","mailbox","doorbell","house key",
    "grocery bag","shopping cart","receipt","coupon","ATM card","cash","coin","piggy bank","bill","invoice",
    "medicine","bandage","thermometer","eye drops","vitamin","glasses","contact lens","hearing aid","crutch","wheelchair",
  ],
  materials: [
    "wood","steel","iron","copper","gold","silver","aluminum","titanium","bronze","brass",
    "tin","zinc","lead","nickel","platinum","chrome","cobalt","tungsten","magnesium","mercury",
    "cotton","wool","silk","linen","hemp","nylon","polyester","leather","rubber","latex",
    "glass","sand","clay","marble","granite","limestone","slate","gravel","concrete","cement",
    "brick","porcelain","ceramic","terracotta","plaster","mortar","asphalt","tar","bitumen","coal",
    "oil","petrol","diesel","charcoal","coke","wax","resin","amber","graphite","silicon",
    "diamond","ruby","emerald","sapphire","pearl","opal","amethyst","topaz","quartz","obsidian",
    "paper","cardboard","cork","bamboo","cane","rattan","wicker","straw","thatch","reed",
    "salt","sugar","flour","cocoa","coffee","tea","yeast","vinegar","gelatin","starch",
    "ivory","bone","shell","horn","fur","feather","parchment","hide","rawhide","sinew",
    "foam","fiber","gel","powder","paste","crystal","alloy","composite","resin","polymer",
    "chalk","coal","sulfur","phosphorus","calcium","nitrogen","carbon","hydrogen","oxygen","helium",
    "ice","steam","mud","ash","soot","rust","mold","wax","tallow","beeswax",
    "obsidian","flint","pumice","sandstone","basalt","quartz","feldspar","mica","talc","gypsum",
    "cotton boll","raw silk","raw wool","raw hide","sap","latex","resin","turpentine","linseed oil","olive oil",
    "pig iron","cast iron","wrought iron","stainless steel","galvanized steel","carbon fiber","fiberglass","kevlar","neoprene","silicone",
    "dye","pigment","ink","paint","varnish","lacquer","glaze","enamel","shellac","epoxy",
    "fertilizer","compost","peat","manure","topsoil","clay soil","loam","silt","humus","mulch",
    "coal tar","crude oil","natural gas","shale","gravel","crushed stone","sand dune","sea salt","rock salt","brine",
  ],
  made_items: [
    "table","chair","bed","wardrobe","shelf","cabinet","desk","drawer","sofa","bench",
    "door","window","wall","roof","floor","pillar","arch","staircase","fence","gate",
    "shirt","jeans","jacket","dress","coat","socks","gloves","scarf","belt","shoe",
    "ring","necklace","bracelet","earring","crown","brooch","pendant","chain","bangle","tiara",
    "bottle","jar","can","box","barrel","bucket","pot","pan","bowl","vase",
    "hammer","saw","knife","wrench","drill","axe","chisel","file","pliers","screwdriver",
    "wire","pipe","cable","nail","bolt","screw","rivet","staple","spring","gear",
    "book","newspaper","envelope","bag","cup","plate","napkin","tissue","card","poster",
    "painting","sculpture","pottery","mosaic","tapestry","carpet","rug","quilt","embroidery","weaving",
    "bread","butter","cheese","wine","beer","oil","chocolate","candle","soap","dye",
    "rope","net","sail","flag","tent","umbrella","parachute","tire","hose","belt",
    "lens","mirror","prism","bulb","screen","coil","magnet","circuit","antenna","battery",
    "coin","medal","trophy","statue","plaque","seal","stamp","key","lock","hinge",
    "arrow","sword","shield","armor","spear","bow","catapult","cannon","bullet","grenade",
    "boat hull","bridge beam","rail","sleeper","road","runway","dam wall","tunnel lining","scaffold","foundation",
    "clay pot","porcelain cup","ceramic tile","glass bead","crystal vase","marble statue","stone carving","wooden mask","ivory figurine","bone tool",
    "cotton thread","silk ribbon","woolen yarn","leather strap","rubber band","nylon rope","polyester fabric","linen sheet","hemp rope","latex glove",
    "paper bag","cardboard box","cork stopper","bamboo basket","rattan chair","wicker basket","straw hat","reed flute","thatch roof","parchment scroll",
    "bronze statue","copper pipe","brass bell","iron gate","steel beam","aluminum foil","tin can","zinc roof","lead pipe","silver spoon",
    "plastic bottle","foam mattress","fiberglass boat","carbon fiber frame","kevlar vest","silicone mold","epoxy joint","lacquered box","enamel pot","glazed tile",
  ],
  actions: [
    "run","walk","jump","climb","swim","fly","crawl","slide","roll","spin",
    "punch","kick","push","pull","lift","throw","catch","hit","beat","smash",
    "open","close","lock","unlock","turn","twist","bend","stretch","squeeze","press",
    "cut","slice","chop","tear","break","snap","crack","crush","grind","scrape",
    "dig","drill","carve","chip","mold","shape","fold","wrap","tie","knot",
    "pour","fill","empty","spill","drip","splash","spray","squirt","soak","rinse",
    "cook","bake","fry","boil","grill","stir","mix","blend","whisk","chop",
    "eat","drink","bite","chew","swallow","spit","lick","taste","smell","sniff",
    "sleep","wake","sit","stand","lean","balance","hang","kneel","bow","salute",
    "wave","point","shake","nod","wink","blink","stare","peek","hide","seek",
    "laugh","cry","scream","whisper","shout","sing","hum","whistle","clap","snap",
    "read","write","draw","paint","type","erase","stamp","sign","mark","underline",
    "plant","water","harvest","prune","dig","rake","mow","weed","fertilize","graft",
    "build","destroy","repair","assemble","dismantle","nail","screw","glue","sew","stitch",
    "drive","steer","brake","accelerate","reverse","park","crash","tow","load","unload",
    "fly","land","takeoff","hover","glide","parachute","dive","surface","dock","anchor",
    "chase","escape","patrol","guard","arrest","attack","defend","dodge","block","tackle",
    "trade","buy","sell","auction","barter","bid","pay","tip","donate","steal",
    "measure","weigh","count","sort","stack","arrange","scatter","collect","search","find",
    "cycle","bounce","skate","ski","surf","paddle","row","sail","tow","haul",
  ],
  countries: [
    "India","China","USA","Brazil","Russia","Canada","Australia","Germany","France","Japan",
    "Italy","Spain","Mexico","Argentina","South Africa","Nigeria","Egypt","Kenya","Ethiopia","Ghana",
    "UK","Ireland","Scotland","Wales","Portugal","Netherlands","Belgium","Switzerland","Austria","Sweden",
    "Norway","Denmark","Finland","Poland","Ukraine","Turkey","Greece","Croatia","Hungary","Romania",
    "Saudi Arabia","UAE","Qatar","Iran","Iraq","Israel","Jordan","Lebanon","Pakistan","Bangladesh",
    "Indonesia","Malaysia","Thailand","Vietnam","Philippines","South Korea","North Korea","Myanmar","Sri Lanka","Nepal",
    "New Zealand","Fiji","Papua New Guinea","Cuba","Jamaica","Haiti","Dominican Republic","Colombia","Peru","Chile",
    "Ecuador","Bolivia","Venezuela","Panama","Costa Rica","Guatemala","Honduras","El Salvador","Nicaragua","Paraguay",
    "Morocco","Algeria","Tunisia","Libya","Sudan","Somalia","Tanzania","Uganda","Zimbabwe","Mozambique",
    "Cameroon","Senegal","Mali","Niger","Chad","Angola","Zambia","Rwanda","Ivory Coast","Madagascar",
    "Iceland","Luxembourg","Malta","Cyprus","Georgia","Armenia","Azerbaijan","Kazakhstan","Uzbekistan","Mongolia",
  ],
};

export const TOPICS = [
  { id: "animals",     label: "🐾 Animals" },
  { id: "food",        label: "🍕 Food" },
  { id: "objects",     label: "🪑 Objects" },
  { id: "vehicles",    label: "🚗 Vehicles" },
  { id: "places",      label: "🏖️ Places" },
  { id: "professions", label: "👷 Professions" },
  { id: "sports",      label: "⚽ Sports" },
  { id: "nature",      label: "🌿 Nature" },
  { id: "actions",     label: "🏃 Actions" },
  { id: "materials",   label: "🪨 Materials" },
  { id: "made_items",  label: "🔨 Made Items" },
  { id: "countries",   label: "🌍 Countries" },
];
